// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZJ7kg0ZYBd_vbn1aXsYWyIV3lbDHUgN8',
    appId: '1:809147543426:web:8cef4276ea2e559a0ca99b',
    messagingSenderId: '809147543426',
    projectId: 'notes-122f6',
    authDomain: 'notes-122f6.firebaseapp.com',
    databaseURL: 'https://notes-122f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-122f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRx07jGG8KtR-EpP7G2zKb_YbeX4Wh0eA',
    appId: '1:809147543426:android:05770b731b5d3ceb0ca99b',
    messagingSenderId: '809147543426',
    projectId: 'notes-122f6',
    databaseURL: 'https://notes-122f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-122f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRzEw-wNT_Es64mjXj1O4EIgu9Qeg1jNg',
    appId: '1:809147543426:ios:fa9fe9b5df5ac9a00ca99b',
    messagingSenderId: '809147543426',
    projectId: 'notes-122f6',
    databaseURL: 'https://notes-122f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-122f6.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRzEw-wNT_Es64mjXj1O4EIgu9Qeg1jNg',
    appId: '1:809147543426:ios:b712a9e484a5b77c0ca99b',
    messagingSenderId: '809147543426',
    projectId: 'notes-122f6',
    databaseURL: 'https://notes-122f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-122f6.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
